# Generated by Django 3.0.8 on 2020-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0003_dht22_humidity_data_dht22_temperature_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Hero',
            },
        ),
    ]
