# Generated by Django 3.0.8 on 2020-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0004_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22_temperature_data',
            name='Date_n_Time',
            field=models.DateTimeField(),
        ),
    ]
