# Generated by Django 3.0.8 on 2020-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0008_auto_20200819_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('proj_gps', models.CharField(max_length=60)),
                ('proj_zip', models.CharField(max_length=60)),
                ('proj_created', models.DateTimeField(auto_now=True)),
                ('proj_last_updated', models.DateTimeField(auto_now=True)),
                ('proj_image', models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=15)),
                ('user_last_name', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=15)),
                ('user_address', models.CharField(max_length=15)),
                ('user_city', models.CharField(max_length=15)),
                ('user_state', models.CharField(max_length=15)),
                ('user_zip', models.CharField(max_length=15)),
                ('user_phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
