# Generated by Django 3.0.8 on 2020-08-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0009_project_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proj_gps',
        ),
        migrations.AddField(
            model_name='project',
            name='proj_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
