# Generated by Django 3.0.8 on 2020-08-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0010_auto_20200823_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_image',
            field=models.ImageField(blank=True, upload_to='image_upload/'),
        ),
    ]
