# Generated by Django 3.0.8 on 2020-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0011_auto_20200823_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_tag',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
