# Generated by Django 3.0.8 on 2020-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0015_auto_20200827_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_details',
            name='device_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='device_details',
            name='device_parameters',
            field=models.CharField(max_length=200),
        ),
    ]
