# Generated by Django 3.0.8 on 2020-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0016_auto_20200827_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_details',
            name='device_tech_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='device_details',
            name='device_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='device_details',
            name='device_parameters',
            field=models.TextField(),
        ),
    ]
