# Generated by Django 3.0.8 on 2020-07-26 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHT22_Humidity_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Humidity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DHT22_Temperature_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('SensorID', models.TextField()),
                ('Date_n_Time', models.TextField()),
                ('Temperature', models.TextField()),
            ],
        ),
    ]
