# Generated by Django 3.0.8 on 2020-07-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_dht22_humidity_data_dht22_temperature_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dht22_humidity_data',
            table='DHT22_Humidity_Data',
        ),
        migrations.AlterModelTable(
            name='dht22_temperature_data',
            table='DHT22_Temperature_Data',
        ),
    ]
