# Generated by Django 3.0.8 on 2020-07-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_auto_20200728_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht22_humidity_data',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dht22_humidity_data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dht22_temperature_data',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dht22_temperature_data',
            name='date',
        ),
    ]
