# Generated by Django 3.0.8 on 2020-07-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_auto_20200730_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DHT22_Humidity_Data',
        ),
        migrations.DeleteModel(
            name='DHT22_Temperature_Data',
        ),
    ]
