# Generated by Django 3.0.8 on 2020-07-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DHT22_Humidity_Data',
        ),
        migrations.DeleteModel(
            name='DHT22_Temperature_Data',
        ),
    ]
